name: Building StoreControl - ${{ github.sha }}
on:
  push:
jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Make IPA
        run: ./ipabuild.sh
      - uses: actions/upload-artifact@v3
        with:
          name: StoreControl-${{ format(github.event.head_commit.timestamp, 'yyyyMMdd') }}-${{ github.sha }}.ipa
          path: build/StoreControl.ipa
