name: ${{ steps.set-name.outputs.commit-message }}
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macos-11
    steps:
      - name: Get latest commit message
        id: set-name
        uses: abeytom/coffee-action@v1.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          command: |
            commit_message=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }} | jq -r '.commit.message' | head -n 1)
            echo "::set-output name=commit-message::$commit_message"
      - uses: actions/checkout@v2
      - name: Make IPA
        run: ./ipabuild.sh
      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: IPA Download
          path: build/StoreControl.ipa
