name: ${{ github.workflow }} - ${{ github.sha }}
on:
  push:
jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Make IPA
        run: ./ipabuild.sh
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.workflow }} - ${{ format(github.event.head_commit.timestamp, 'yyyy-MM-dd') }}
          path: build/StoreControl.ipa
