name: Build StoreControl
on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: macos-11

    steps:
    - name: Set artifact name
      run: |
        echo "artifact_name=StoreControl-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

    - uses: actions/checkout@v2

    - name: Make IPA
      run: ./ipabuild.sh

    - name: Upload IPA artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.artifact_name }}
        path: build/StoreControl.ipa
        
  set-env-vars:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Set workflow run title
        run: |
          MESSAGE=$(git log -1 --pretty=format:%s $GITHUB_SHA)
          echo "::set-env name=ACTION_TITLE::$MESSAGE"
